### PR TITLE
Issue #117: removing edp-sub-layout from project as the project is not on packagist

### PR DESCRIPTION
**Pull request by DragonBe**

### CODE REVIEW

**Comment by shipleyr** [comment]
You can't just pull the dependant. By doing that you will break all of the admin system as it stands at the moment.

**Comment by DragonBe** [comment]
Oops, my bad… wasn't paying attention to it. Will close this one and commit a new PR.

**Comment by Xerkus** [comment]
added sublayout to packagist

**Comment by DragonBe** [comment]
So we can actually close this PR as it is no longer an issue… even better :+1:

**Pull request closed without merging**
